In [1]:
pip install google-play-scraper pandas nltk stanza seaborn matplotlib scikit-learn Sastrawi

Requirement already satisfied: google-play-scraper in c:\coding\pba\pba-tixid-sentimentanalysis\week-2\.venv\lib\site-packages (1.2.7)
Requirement already satisfied: pandas in c:\coding\pba\pba-tixid-sentimentanalysis\week-2\.venv\lib\site-packages (3.0.1)
Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
     ---------------------------------------- 1.6/1.6 MB 5.2 MB/s eta 0:00:00
Collecting stanza
  Downloading stanza-1.11.1-py3-none-any.whl (1.7 MB)
     ---------------------------------------- 1.7/1.7 MB 9.0 MB/s eta 0:00:00
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
     -------------------------------------- 294.9/294.9 kB 9.2 MB/s eta 0:00:00
Collecting matplotlib
  Downloading matplotlib-3.10.8-cp311-cp311-win_amd64.whl (8.1 MB)
     ---------------------------------------- 8.1/8.1 MB 9.3 MB/s eta 0:00:00
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
     ---------------------------------------- 8.1/8.1 MB 7.0 MB/s eta 0:00:00
Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
     -------------------------------------- 209.7/209.7 kB 6.4 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.26.0 in c:\coding\pba\pba-tixid-sentimentanalysis\week-2\.venv\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\coding\pba\pba-tixid-sentimentanalysis\week-2\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\coding\pba\pba-tixid-sentimentanalysis\week-2\.venv\lib\site-packages (from pandas) (2025.3)
Collecting click
  Downloading click-8.3.1-py3-none-any.whl (108 kB)
     -------------------------------------- 108.3/108.3 kB 6.5 MB/s eta 0:00:00
Collecting joblib
  Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
     -------------------------------------- 309.1/309.1 kB 6.5 MB/s eta 0:00:00
Collecting regex>=2021.8.3
  Downloading regex-2026.2.28-cp311-cp311-win_amd64.whl (277 kB)
     -------------------------------------- 278.0/278.0 kB 4.2 MB/s eta 0:00:00
Collecting tqdm
  Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
     ---------------------------------------- 78.4/78.4 kB 2.2 MB/s eta 0:00:00
Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
     -------------------------------------- 608.4/608.4 kB 7.7 MB/s eta 0:00:00
Requirement already satisfied: platformdirs in c:\coding\pba\pba-tixid-sentimentanalysis\week-2\.venv\lib\site-packages (from stanza) (4.9.4)
Collecting protobuf>=3.15.0
  Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl (437 kB)
     -------------------------------------- 437.9/437.9 kB 6.9 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     ---------------------------------------- 64.7/64.7 kB 3.6 MB/s eta 0:00:00
Collecting networkx
  Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 8.8 MB/s eta 0:00:00
Collecting torch>=1.13.0
  Downloading torch-2.11.0-cp311-cp311-win_amd64.whl (114.5 MB)
     -------------------------------------- 114.5/114.5 MB 5.8 MB/s eta 0:00:00
Collecting udtools>=0.2.4
  Downloading udtools-0.2.7-py3-none-any.whl (773 kB)
     -------------------------------------- 773.7/773.7 kB 7.0 MB/s eta 0:00:00
Collecting contourpy>=1.0.1
  Downloading contourpy-1.3.3-cp311-cp311-win_amd64.whl (225 kB)
     -------------------------------------- 225.2/225.2 kB 6.9 MB/s eta 0:00:00
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.62.1-cp311-cp311-win_amd64.whl (2.3 MB)
     ---------------------------------------- 2.3/2.3 MB 5.7 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.5.0-cp311-cp311-win_amd64.whl (73 kB)
     ---------------------------------------- 73.5/73.5 kB 4.0 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in c:\coding\pba\pba-tixid-sentimentanalysis\week-2\.venv\lib\site-packages (from matplotlib) (26.0)
Collecting pillow>=8
  Downloading pillow-12.1.1-cp311-cp311-win_amd64.whl (7.0 MB)
     ---------------------------------------- 7.0/7.0 MB 8.5 MB/s eta 0:00:00
Collecting pyparsing>=3
  Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
     -------------------------------------- 122.8/122.8 kB 3.6 MB/s eta 0:00:00
Collecting scipy>=1.10.0
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
     ---------------------------------------- 36.6/36.6 MB 8.5 MB/s eta 0:00:00
Collecting threadpoolctl>=3.2.0
  Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Requirement already satisfied: six>=1.5 in c:\coding\pba\pba-tixid-sentimentanalysis\week-2\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting filelock
  Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\coding\pba\pba-tixid-sentimentanalysis\week-2\.venv\lib\site-packages (from torch>=1.13.0->stanza) (4.15.0)
Requirement already satisfied: setuptools<82 in c:\coding\pba\pba-tixid-sentimentanalysis\week-2\.venv\lib\site-packages (from torch>=1.13.0->stanza) (65.5.0)
Collecting sympy>=1.13.3
  Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
     ---------------------------------------- 6.3/6.3 MB 8.4 MB/s eta 0:00:00
Collecting jinja2
  Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
     -------------------------------------- 134.9/134.9 kB 4.0 MB/s eta 0:00:00
Collecting fsspec>=0.8.5
  Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
     -------------------------------------- 202.5/202.5 kB 6.2 MB/s eta 0:00:00
Collecting udapi>=0.5.0
  Downloading udapi-0.5.2-py3-none-any.whl (418 kB)
     -------------------------------------- 418.7/418.7 kB 8.9 MB/s eta 0:00:00
Requirement already satisfied: colorama in c:\coding\pba\pba-tixid-sentimentanalysis\week-2\.venv\lib\site-packages (from click->nltk) (0.4.6)
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.6-cp311-cp311-win_amd64.whl (153 kB)
     -------------------------------------- 153.9/153.9 kB 4.6 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.11-py3-none-any.whl (71 kB)
     ---------------------------------------- 71.0/71.0 kB 3.8 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
     -------------------------------------- 131.6/131.6 kB 8.1 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
     -------------------------------------- 153.7/153.7 kB 4.6 MB/s eta 0:00:00
Collecting mpmath<1.4,>=1.1.0
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
     -------------------------------------- 536.2/536.2 kB 8.5 MB/s eta 0:00:00
Collecting termcolor
  Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Collecting MarkupSafe>=2.0
  Downloading markupsafe-3.0.3-cp311-cp311-win_amd64.whl (15 kB)
Installing collected packages: Sastrawi, mpmath, urllib3, tqdm, threadpoolctl, termcolor, sympy, scipy, regex, pyparsing, protobuf, pillow, networkx, MarkupSafe, kiwisolver, joblib, idna, fsspec, fonttools, filelock, emoji, cycler, contourpy, click, charset_normalizer, certifi, udapi, scikit-learn, requests, nltk, matplotlib, jinja2, udtools, torch, seaborn, stanza
Successfully installed MarkupSafe-3.0.3 Sastrawi-1.0.1 certifi-2026.2.25 charset_normalizer-3.4.6 click-8.3.1 contourpy-1.3.3 cycler-0.12.1 emoji-2.15.0 filelock-3.25.2 fonttools-4.62.1 fsspec-2026.2.0 idna-3.11 jinja2-3.1.6 joblib-1.5.3 kiwisolver-1.5.0 matplotlib-3.10.8 mpmath-1.3.0 networkx-3.6.1 nltk-3.9.4 pillow-12.1.1 protobuf-7.34.1 pyparsing-3.3.2 regex-2026.2.28 requests-2.32.5 scikit-learn-1.8.0 scipy-1.17.1 seaborn-0.13.2 stanza-1.11.1 sympy-1.14.0 termcolor-3.3.0 threadpoolctl-3.6.0 torch-2.11.0 tqdm-4.67.3 udapi-0.5.2 udtools-0.2.7 urllib3-2.6.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# **1. Scraping Review Aplikasi TIX ID**

In [2]:
from google_play_scraper import reviews_all, Sort
import pandas as pd

tix_reviews = reviews_all(
    'id.tix.android',
    lang='id',
    country='id',
    sort=Sort.NEWEST
)

df = pd.DataFrame(tix_reviews)
df = df[['content', 'score', 'at']]
df = df.dropna(subset=['content'])
df == df[df['content'].str.strip() != '']

print(f'Total Review: {len(df)}')
df.head()

df.to_excel('tix_id_reviews.xlsx', index=False)

Total Review: 96284

# **2. Label Sentiment dari Rating**

In [3]:
def label_sentiment(score: int) -> str:
  if score >= 4:
    return 'Positive'
  elif score == 3:
    return 'Neutral'
  else:
    return 'Negative'

df['sentiment'] = df['score'].apply(label_sentiment)
df.head()

,content,score,at,sentiment
0,sangat ramai pengunjung,5,2026-03-23 18:34:22,Positive
1,aplikasi sangat amat tidak berguna. karna buka...,1,2026-03-23 14:20:58,Negative
2,"keren film nya, film yang mendidik",5,2026-03-23 10:14:14,Positive
3,gooooooooood,5,2026-03-23 09:52:56,Positive
4,dengan apikasi digi sangat membantu untuk book...,5,2026-03-23 04:40:21,Positive

# **3. Regex Cleaning**

In [4]:
import re

def clean_text(text: str) -> str:
  text = text.lower()
  text = re.sub(r'http\S+', '', text)
  text = re.sub(r'@\w+', '', text)
  text = re.sub(r'[^a-zA-Z\s]', ' ', text)
  text = re.sub(r'(.)\1{2,}', r'\1', text)
  text = re.sub(r'\s+', ' ', text).strip()
  return text

df['clean_content'] = df['content'].apply(clean_text)

df.head()

,content,score,at,sentiment,clean_content
0,sangat ramai pengunjung,5,2026-03-23 18:34:22,Positive,sangat ramai pengunjung
1,aplikasi sangat amat tidak berguna. karna buka...,1,2026-03-23 14:20:58,Negative,aplikasi sangat amat tidak berguna karna bukan...
2,"keren film nya, film yang mendidik",5,2026-03-23 10:14:14,Positive,keren film nya film yang mendidik
3,gooooooooood,5,2026-03-23 09:52:56,Positive,god
4,dengan apikasi digi sangat membantu untuk book...,5,2026-03-23 04:40:21,Positive,dengan apikasi digi sangat membantu untuk book...

# **4. Stopword Removal**

In [5]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stop = stopwords.words('indonesian')

df['no_stopwords'] = df['clean_content'].apply(
    lambda x: ' '.join([word for word in x.split() if word not in stop])
)

df.head()

[nltk_data] Downloading package stopwords to C:\Users\Ratna
[nltk_data]     Amalia\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

,content,score,at,sentiment,clean_content,no_stopwords
0,sangat ramai pengunjung,5,2026-03-23 18:34:22,Positive,sangat ramai pengunjung,ramai pengunjung
1,aplikasi sangat amat tidak berguna. karna buka...,1,2026-03-23 14:20:58,Negative,aplikasi sangat amat tidak berguna karna bukan...,aplikasi berguna karna bukanya cepat beli tike...
2,"keren film nya, film yang mendidik",5,2026-03-23 10:14:14,Positive,keren film nya film yang mendidik,keren film nya film mendidik
3,gooooooooood,5,2026-03-23 09:52:56,Positive,god,god
4,dengan apikasi digi sangat membantu untuk book...,5,2026-03-23 04:40:21,Positive,dengan apikasi digi sangat membantu untuk book...,apikasi digi membantu booking film film

# **5. Tokenization**

In [6]:
def tokenize(text: str):
  return text.split()

df['tokens'] = df['no_stopwords'].apply(tokenize)

df.head()

,content,score,at,sentiment,clean_content,no_stopwords,tokens
0,sangat ramai pengunjung,5,2026-03-23 18:34:22,Positive,sangat ramai pengunjung,ramai pengunjung,"[ramai, pengunjung]"
1,aplikasi sangat amat tidak berguna. karna buka...,1,2026-03-23 14:20:58,Negative,aplikasi sangat amat tidak berguna karna bukan...,aplikasi berguna karna bukanya cepat beli tike...,"[aplikasi, berguna, karna, bukanya, cepat, bel..."
2,"keren film nya, film yang mendidik",5,2026-03-23 10:14:14,Positive,keren film nya film yang mendidik,keren film nya film mendidik,"[keren, film, nya, film, mendidik]"
3,gooooooooood,5,2026-03-23 09:52:56,Positive,god,god,[god]
4,dengan apikasi digi sangat membantu untuk book...,5,2026-03-23 04:40:21,Positive,dengan apikasi digi sangat membantu untuk book...,apikasi digi membantu booking film film,"[apikasi, digi, membantu, booking, film, film]"

# **6. Stemming**

In [7]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(text: str):
  return stemmer.stem(text)

df['stemmed'] = df['no_stopwords'].apply(stemming)

df.head()

,content,score,at,sentiment,clean_content,no_stopwords,tokens,stemmed
0,sangat ramai pengunjung,5,2026-03-23 18:34:22,Positive,sangat ramai pengunjung,ramai pengunjung,"[ramai, pengunjung]",ramai unjung
1,aplikasi sangat amat tidak berguna. karna buka...,1,2026-03-23 14:20:58,Negative,aplikasi sangat amat tidak berguna karna bukan...,aplikasi berguna karna bukanya cepat beli tike...,"[aplikasi, berguna, karna, bukanya, cepat, bel...",aplikasi guna karna buka cepat beli tiket doub...
2,"keren film nya, film yang mendidik",5,2026-03-23 10:14:14,Positive,keren film nya film yang mendidik,keren film nya film mendidik,"[keren, film, nya, film, mendidik]",keren film nya film didik
3,gooooooooood,5,2026-03-23 09:52:56,Positive,god,god,[god],god
4,dengan apikasi digi sangat membantu untuk book...,5,2026-03-23 04:40:21,Positive,dengan apikasi digi sangat membantu untuk book...,apikasi digi membantu booking film film,"[apikasi, digi, membantu, booking, film, film]",apikasi digi bantu booking film film

# **7. POS Tagging dgn Stanza**

In [8]:
import stanza

stanza.download('id')
nlp = stanza.Pipeline('id')

def pos_tagging(text: str):
  doc = nlp(text)
  result = []
  for sentence in doc.sentences:
    for word in sentence.words:
      result.append((word.text, word.upos))
  return result

print(pos_tagging(df['no_stopwords'].iloc[0]))

c:\Coding\pba\PBA-TIXID-SentimentAnalysis\Week-2\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 10.7MB/s]
2026-03-24 19:21:38 INFO: Downloaded file to C:\Users\Ratna Amalia\AppData\Local\StanfordNLP\stanza\Cache\1.11.0\resources\resources.json
2026-03-24 19:21:38 INFO: Downloading default packages for language: id (Indonesian) ...
Downloading https://huggingface.co/stanfordnlp/stanza-id/resolve/v1.11.0/models/default.zip: 100%|██████████| 396M/396M [00:50<00:00, 7.84MB/s]
2026-03-24 19:22:30 INFO: Downloaded file to C:\Users\Ratna Amalia\AppData\Local\StanfordNLP\stanza\Cache\1.11.0\resources\id\default.zip
2026-03-24 19:22:33 INFO: Finished downloading models and saved to C:\Users\Ratna Amalia\AppData\Local\StanfordNLP\stanza\Cache\1.11.0\resources
2026-03-24 19:22:33 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 10.1MB/s]
2026-03-24 19:22:34 INFO: Downloaded file to C:\Users\Ratna Amalia\AppData\Local\StanfordNLP\stanza\Cache\1.11.0\resources\resources.json
2026-03-24 19:22:35 INFO: Loading these models for language: id (Indonesian):
===============================
| Processor    | Package      |
-------------------------------
| tokenize     | gsd          |
| mwt          | gsd          |
| pos          | gsd_charlm   |
| lemma        | gsd_nocharlm |
| constituency | icon_charlm  |
| depparse     | gsd_charlm   |
===============================

2026-03-24 19:22:35 INFO: Using device: cpu
2026-03-24 19:22:35 INFO: Loading: tokenize
2026-03-24 19:22:38 INFO: Loading: mwt
2026-03-24 19:22:38 INFO: Loading: pos
2026-03-24 19:22:41 INFO: Loading: lemma
2026-03-24 19:22:41 INFO: Loading: constituency
2026-03-24 19:22:42 INFO: Loading: depparse
2026-03-24 19:22:42 INFO: Done loading processors!

[('ramai', 'ADJ'), ('pengunjung', 'NOUN')]

# **8. Hitung Distribusi POS**

In [3]:
from collections import Counter

df_pos_sample = df.sample(600, random_state=42)

def get_pos_counts(text: str):
  doc = nlp(text)
  pos_list = []
  for sentence in doc.sentences:
    for word in sentence.words:
      pos_list.append(word.upos)
  return Counter(pos_list)

df_pos_sample['pos_counts'] = df['no_stopwords'].apply(get_pos_counts)
df.head()

NameError: name 'df' is not defined

# **9. Hitung Adjectve**

In [ ]:
def count_adj(text: str) -> int:
  doc = nlp(text)
  count = 0
  for sentence in doc.sentences:
    for word in sentence.words:
      if word.upos == 'ADJ':
        count += 1
  return count

df_pos_sample['adj_count'] = df_pos_sample['no_stopwords'].apply(count_adj)
df.head()

# **10. Visualisasi Rating**

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure()
sns.countplot(x='score', data=df)
plt.title('Distribus Rating Aplikasi TIX ID')
plt.show()

# **11. TF-IDF Feature Extraction**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))

X = vectorizer.fit_transform(df['stemmed'])
y = df['sentiment']

# **12. Bag of Words (BoW)**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

bow_vectorizer = CountVectorizer()

X_bow = bow_vectorizer.fit_transform(df['stemmed'])

print("BoW Shape:":, X_bow.shape)

# **13. N-Gram Feature**

In [ ]:
ngram_vectorizer = CountVectorizer(
    ngram_range=(1, 2),
    max_features=5000
)

X_ngram = ngram_vectorizer.fit_transform(df['stemmed'])

print("N-Gram Shape:", X_ngram.shape)

# **14. Train, Test, Split**

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# **15. Model 1 - Naive Bayes**

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score

nb = MultinomialNB()
nb.fit(X_train, y_train)

y_pred_nb = nb.predict(X_test)

print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

# **16. Model 2 - Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print ("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

# **17. Model 3 - SVM**

In [ ]:
from sklearn.svm import LinearSVC
svm = LinearSVC()
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

# **18. Perbandingan Accuracy Model**

In [ ]:
results = {
    "Naive Bayes": accuracy_score(y_test, y_pred_nb),
    "Logistic Regression": accuracy_score(y_test, y_pred_lr),
    "SVM": accuracy_score(y_test, y_pred_svm),
}

print(results)

# **19. Visualisasi Perbandingan Model**

In [ ]:
plt.figure()
plt.bar(results.keys(), results.values())
plt.title("Perbandingan Accuracy Model Sentiment Analysis")
plt.ylabel("Accuracy")
plt.show()